# Generated by Django 3.0.2 on 2020-02-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
