# Generated by Django 3.0.2 on 2020-03-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200305_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
