# Generated by Django 3.0.2 on 2020-03-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200305_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='user',
        ),
        migrations.DeleteModel(
            name='Addresses',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
