# Generated by Django 3.0.2 on 2020-03-05 07:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_addresses_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4331),
        ),
    ]
