# Generated by Django 3.0.2 on 2020-03-05 07:41

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_addresses_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
