# Generated by Django 3.0.2 on 2020-03-05 07:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_addresses_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
