# Generated by Django 3.0.2 on 2020-03-05 07:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200305_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
