# Generated by Django 3.0.2 on 2020-03-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200305_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
    ]
