# Generated by Django 3.0.2 on 2020-03-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_addresses_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
