# Generated by Django 3.0.2 on 2020-03-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200305_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True),
        ),
    ]
