# Generated by Django 3.0.2 on 2020-03-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200305_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresses',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='bindingConfig',
            new_name='binding_config',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='printingConfig',
            new_name='printing_config',
        ),
    ]
