# Generated by Django 3.0.2 on 2020-03-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_order_multi_color_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='front_cover_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
