# Generated by Django 3.0.2 on 2020-03-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200306_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
