# Generated by Django 3.0.2 on 2020-03-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20200306_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='price_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('dynamic', 'Dynamic'), ('per_page', 'Per Page')], default='per_page', max_length=20),
            preserve_default=False,
        ),
    ]
