# Generated by Django 3.0.2 on 2020-03-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200306_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.CharField(choices=[('print', 'Print'), ('binding', 'Binding'), ('paper', 'Paper'), ('others', 'Others')], max_length=20),
        ),
    ]
