# Generated by Django 3.0.2 on 2020-03-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20200309_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='price_list',
        ),
    ]
