# Generated by Django 3.0.2 on 2020-03-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20200309_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf_page_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
