# Generated by Django 3.0.2 on 2020-03-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_order_pdf_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='configurations',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', to='api.Configuration'),
        ),
    ]
