# Generated by Django 3.0.2 on 2020-03-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
