# Generated by Django 3.0.2 on 2020-03-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_order_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='configurations',
            field=models.ManyToManyField(related_name='orders', to='api.Configuration'),
        ),
    ]
