# Generated by Django 3.0.2 on 2020-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20200311_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(auto_created=True, choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('departed', 'Departed'), ('completed', 'Completed')], default='accepted', max_length=20),
        ),
    ]
