# Generated by Django 3.0.2 on 2020-03-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20200311_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
