# Generated by Django 3.0.2 on 2020-03-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_user_isstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isStudent',
            new_name='is_student',
        ),
    ]
