# Generated by Django 3.0.2 on 2020-03-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_auto_20200312_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No')], default=True, null=True),
        ),
    ]
