# Generated by Django 3.0.2 on 2020-03-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20200312_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_freemium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
    ]
