# Generated by Django 3.0.2 on 2020-03-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20200313_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_freemium',
            field=models.BooleanField(default=True),
        ),
    ]
