# Generated by Django 3.0.2 on 2020-03-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20200314_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
