# Generated by Django 3.0.2 on 2020-03-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20200316_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='type',
            field=models.CharField(choices=[('print', 'Print'), ('binding', 'Binding'), ('page', 'Page'), ('paper', 'Paper'), ('others', 'Others')], max_length=20),
        ),
    ]
