# Generated by Django 3.0.2 on 2020-03-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_auto_20200318_0616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='page_config',
        ),
    ]
