# Generated by Django 3.0.2 on 2020-03-18 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_order_page_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_address', to='api.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='configurations',
            field=models.ManyToManyField(null=True, related_name='orders', to='api.Configuration'),
        ),
    ]
