# Generated by Django 3.0.2 on 2020-03-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20200318_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='configurations',
            field=models.ManyToManyField(blank=True, related_name='orders', to='api.Configuration'),
        ),
    ]
