# Generated by Django 3.0.2 on 2020-03-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_auto_20200318_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
