# Generated by Django 3.0.2 on 2020-03-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20200319_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
