# Generated by Django 3.0.2 on 2020-03-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20200319_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_name',
            field=models.CharField(default="Adam's", max_length=255),
            preserve_default=False,
        ),
    ]
