# Generated by Django 3.0.2 on 2020-03-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_assignedorder'),
        ('api', '0090_auto_20200319_0736'),
    ]

    operations = [
    ]
