# Generated by Django 3.0.2 on 2020-03-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_merge_20200319_1137'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignedorder',
            table='assigned_orders',
        ),
    ]
