# Generated by Django 3.0.2 on 2020-03-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20200319_1146'),
        ('api', '0092_user_created_at'),
    ]

    operations = [
    ]
