# Generated by Django 3.0.2 on 2020-03-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_merge_20200319_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
