# Generated by Django 3.0.2 on 2020-03-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='departed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='processing_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(auto_created=True, choices=[('incomplete', 'Incomplete'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned'), ('processing', 'Processing'), ('departed', 'Departed'), ('delivered', 'Delivered')], default='confirmed', max_length=20),
        ),
    ]
