# Generated by Django 3.0.2 on 2020-03-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
