# Generated by Django 3.0.2 on 2020-03-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_order_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
