# Generated by Django 3.0.2 on 2020-03-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
