# Generated by Django 3.0.2 on 2020-03-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_user_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='type',
        ),
        migrations.AddField(
            model_name='address',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='pin_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
