# Generated by Django 3.0.2 on 2020-03-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_auto_20200325_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payment_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
