# Generated by Django 3.0.2 on 2020-03-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_order_is_payment_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
    ]
