# Generated by Django 3.0.2 on 2020-05-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20200509_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('freemium', 'Freemium'), ('standard_print', 'Standard Print'), ('official_documents', 'Official Documents')], max_length=20, null=True),
        ),
    ]
