# Generated by Django 3.0.2 on 2020-05-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_order_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_id',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
