# Generated by Django 3.0.2 on 2020-06-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_configuration_strike_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sem',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=5, null=True),
        ),
    ]
