# Generated by Django 3.0.2 on 2020-06-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_auto_20200610_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
    ]
