# Generated by Django 3.0.2 on 2020-06-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_auto_20200610_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sem',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
    ]
