# Generated by Django 3.0.2 on 2020-06-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0126_auto_20200610_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='per_page_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
