# Generated by Django 3.0.2 on 2020-06-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_configuration_per_page_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='config_list',
            field=models.TextField(blank=True, null=True),
        ),
    ]
