# Generated by Django 3.1.3 on 2020-11-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_auto_20200624_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('validity', models.DateTimeField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('count', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('redirection_url', models.CharField(blank=True, default='', max_length=60, null=True)),
            ],
            options={
                'db_table': 'qr_code',
            },
        ),
    ]
