# Generated by Django 3.1.3 on 2020-12-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0133_material_userqrorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userqrorder',
            name='material',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
