# Generated by Django 3.1.3 on 2020-12-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0134_auto_20201204_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
